//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COLSTRAT.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COLSTRAT.Resources.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change.
        /// </summary>
        public static string btn_change_pass {
            get {
                return ResourceManager.GetString("btn_change_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Types of rocks.
        /// </summary>
        public static string btn_rocks_types {
            get {
                return ResourceManager.GetString("btn_rocks_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show.
        /// </summary>
        public static string btnShow {
            get {
                return ResourceManager.GetString("btnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string btnSignUp {
            get {
                return ResourceManager.GetString("btnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check your internet connection.
        /// </summary>
        public static string check_internet_connection {
            get {
                return ResourceManager.GetString("check_internet_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check your internet settings.
        /// </summary>
        public static string check_internet_settings {
            get {
                return ResourceManager.GetString("check_internet_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure?.
        /// </summary>
        public static string confirm_exit {
            get {
                return ResourceManager.GetString("confirm_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string confirm_pass {
            get {
                return ResourceManager.GetString("confirm_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create New.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Category.
        /// </summary>
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Menu.
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are a record with the same email..
        /// </summary>
        public static string email_exists {
            get {
                return ResourceManager.GetString("email_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We can&apos;t send the new password to this email..
        /// </summary>
        public static string error_cant_send_passtoemail {
            get {
                return ResourceManager.GetString("error_cant_send_passtoemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a new password confirm..
        /// </summary>
        public static string error_confirm_input_pass {
            get {
                return ResourceManager.GetString("error_confirm_input_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a valid email..
        /// </summary>
        public static string error_email_invalid {
            get {
                return ResourceManager.GetString("error_email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a category.
        /// </summary>
        public static string error_input_category {
            get {
                return ResourceManager.GetString("error_input_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter the current password..
        /// </summary>
        public static string error_input_current_pass {
            get {
                return ResourceManager.GetString("error_input_current_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter an email..
        /// </summary>
        public static string error_input_email_0 {
            get {
                return ResourceManager.GetString("error_input_email_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a first name..
        /// </summary>
        public static string error_input_first_name {
            get {
                return ResourceManager.GetString("error_input_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a last name..
        /// </summary>
        public static string error_input_last_name {
            get {
                return ResourceManager.GetString("error_input_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a menu.
        /// </summary>
        public static string error_input_menu {
            get {
                return ResourceManager.GetString("error_input_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a new password..
        /// </summary>
        public static string error_input_new_pass {
            get {
                return ResourceManager.GetString("error_input_new_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a password confirm..
        /// </summary>
        public static string error_input_pass_confirm {
            get {
                return ResourceManager.GetString("error_input_pass_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a password..
        /// </summary>
        public static string error_input_password_0 {
            get {
                return ResourceManager.GetString("error_input_password_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new password must have at least 6 characters length..
        /// </summary>
        public static string error_lenght_new_pass {
            get {
                return ResourceManager.GetString("error_lenght_new_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must have at least 6 characters length..
        /// </summary>
        public static string error_pass_length {
            get {
                return ResourceManager.GetString("error_pass_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current password is not valid.
        /// </summary>
        public static string error_pass_not_valid {
            get {
                return ResourceManager.GetString("error_pass_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are a record with the same description.
        /// </summary>
        public static string error_record_same {
            get {
                return ResourceManager.GetString("error_record_same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t delete this record, because it has related records.
        /// </summary>
        public static string error_relateds {
            get {
                return ResourceManager.GetString("error_relateds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The service is not available, please try latter..
        /// </summary>
        public static string error_service_no_available {
            get {
                return ResourceManager.GetString("error_service_no_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problem ocurred retrieving user information, try latter..
        /// </summary>
        public static string error_user_information {
            get {
                return ResourceManager.GetString("error_user_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name:.
        /// </summary>
        public static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your Password?.
        /// </summary>
        public static string ForgotPass {
            get {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From camera.
        /// </summary>
        public static string from_camera {
            get {
                return ResourceManager.GetString("from_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From gallery.
        /// </summary>
        public static string from_gallery {
            get {
                return ResourceManager.GetString("from_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Igneous Rocks.
        /// </summary>
        public static string IgneousRocks {
            get {
                return ResourceManager.GetString("IgneousRocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address:.
        /// </summary>
        public static string label_addres {
            get {
                return ResourceManager.GetString("label_addres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category:.
        /// </summary>
        public static string label_Category {
            get {
                return ResourceManager.GetString("label_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm New Password.
        /// </summary>
        public static string label_confirm_new_pass {
            get {
                return ResourceManager.GetString("label_confirm_new_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Password.
        /// </summary>
        public static string label_current_password {
            get {
                return ResourceManager.GetString("label_current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description:.
        /// </summary>
        public static string label_description {
            get {
                return ResourceManager.GetString("label_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string label_email {
            get {
                return ResourceManager.GetString("label_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image:.
        /// </summary>
        public static string label_image {
            get {
                return ResourceManager.GetString("label_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item:.
        /// </summary>
        public static string label_item {
            get {
                return ResourceManager.GetString("label_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name:.
        /// </summary>
        public static string label_last_name {
            get {
                return ResourceManager.GetString("label_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu:.
        /// </summary>
        public static string label_menu {
            get {
                return ResourceManager.GetString("label_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minerals:.
        /// </summary>
        public static string label_minerals {
            get {
                return ResourceManager.GetString("label_minerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        public static string label_name {
            get {
                return ResourceManager.GetString("label_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string label_new_password {
            get {
                return ResourceManager.GetString("label_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string label_password {
            get {
                return ResourceManager.GetString("label_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone:.
        /// </summary>
        public static string label_phone {
            get {
                return ResourceManager.GetString("label_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press sync button to start.
        /// </summary>
        public static string label_sync_info {
            get {
                return ResourceManager.GetString("label_sync_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User or Email.
        /// </summary>
        public static string label_user {
            get {
                return ResourceManager.GetString("label_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rocks loaded from api..
        /// </summary>
        public static string loaded_api {
            get {
                return ResourceManager.GetString("loaded_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rocks loaded from local data..
        /// </summary>
        public static string loaded_local {
            get {
                return ResourceManager.GetString("loaded_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string LoginViewTitle {
            get {
                return ResourceManager.GetString("LoginViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login with Facebook.
        /// </summary>
        public static string LoginWithFacebook {
            get {
                return ResourceManager.GetString("LoginWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main menu.
        /// </summary>
        public static string MainMenuViewTitle {
            get {
                return ResourceManager.GetString("MainMenuViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string menu_profile {
            get {
                return ResourceManager.GetString("menu_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubication.
        /// </summary>
        public static string menu_ubication {
            get {
                return ResourceManager.GetString("menu_ubication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sure?.
        /// </summary>
        public static string message_delete {
            get {
                return ResourceManager.GetString("message_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string message_image {
            get {
                return ResourceManager.GetString("message_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Does this image look good?.
        /// </summary>
        public static string message_image_content {
            get {
                return ResourceManager.GetString("message_image_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dear user, don&apos;t have connection and also has data information.
        /// </summary>
        public static string message_not_data {
            get {
                return ResourceManager.GetString("message_not_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don&apos;t hav items for sync.
        /// </summary>
        public static string message_not_data_forsync {
            get {
                return ResourceManager.GetString("message_not_data_forsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have not chosen a rock to show.
        /// </summary>
        public static string message_not_select_rock {
            get {
                return ResourceManager.GetString("message_not_select_rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product was save on local DB don&apos;t forget to upload the record when you have WiFi.
        /// </summary>
        public static string message_save_onlocaldb {
            get {
                return ResourceManager.GetString("message_save_onlocaldb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string message_title {
            get {
                return ResourceManager.GetString("message_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metamorphic Rocks.
        /// </summary>
        public static string MetamorphicRocks {
            get {
                return ResourceManager.GetString("MetamorphicRocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Category.
        /// </summary>
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register new user.
        /// </summary>
        public static string NewCustomerViewTitle {
            get {
                return ResourceManager.GetString("NewCustomerViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New menu.
        /// </summary>
        public static string NewMenu {
            get {
                return ResourceManager.GetString("NewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string not {
            get {
                return ResourceManager.GetString("not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Where do you take the image?.
        /// </summary>
        public static string option_select_image {
            get {
                return ResourceManager.GetString("option_select_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password was changed successfully.
        /// </summary>
        public static string pass_change_success {
            get {
                return ResourceManager.GetString("pass_change_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password and confirm, does not match..
        /// </summary>
        public static string pass_confirm_notmatch {
            get {
                return ResourceManager.GetString("pass_confirm_notmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the rock.
        /// </summary>
        public static string picker_select_the_rock {
            get {
                return ResourceManager.GetString("picker_select_the_rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the address....
        /// </summary>
        public static string placeholder_addres {
            get {
                return ResourceManager.GetString("placeholder_addres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a category name.
        /// </summary>
        public static string placeholder_category {
            get {
                return ResourceManager.GetString("placeholder_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a category description....
        /// </summary>
        public static string placeholder_category_description {
            get {
                return ResourceManager.GetString("placeholder_category_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the password confirm....
        /// </summary>
        public static string placeholder_confirm_pass {
            get {
                return ResourceManager.GetString("placeholder_confirm_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a description....
        /// </summary>
        public static string placeholder_description_item {
            get {
                return ResourceManager.GetString("placeholder_description_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your email....
        /// </summary>
        public static string placeholder_email {
            get {
                return ResourceManager.GetString("placeholder_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the first name....
        /// </summary>
        public static string placeholder_first_name {
            get {
                return ResourceManager.GetString("placeholder_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a name.
        /// </summary>
        public static string placeholder_item {
            get {
                return ResourceManager.GetString("placeholder_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the last name....
        /// </summary>
        public static string placeholder_last_name {
            get {
                return ResourceManager.GetString("placeholder_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter menu description....
        /// </summary>
        public static string placeholder_menu_description {
            get {
                return ResourceManager.GetString("placeholder_menu_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter menu icon....
        /// </summary>
        public static string placeholder_menu_icon {
            get {
                return ResourceManager.GetString("placeholder_menu_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your password....
        /// </summary>
        public static string placeholder_password {
            get {
                return ResourceManager.GetString("placeholder_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the phone....
        /// </summary>
        public static string placeholder_phone {
            get {
                return ResourceManager.GetString("placeholder_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rocks.
        /// </summary>
        public static string RocksTitle {
            get {
                return ResourceManager.GetString("RocksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search....
        /// </summary>
        public static string SearchBarPlaceholder {
            get {
                return ResourceManager.GetString("SearchBarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sedimentary Rocks.
        /// </summary>
        public static string SedimentaryRocks {
            get {
                return ResourceManager.GetString("SedimentaryRocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your new password has been sent to your email!.
        /// </summary>
        public static string send_new_pass_success {
            get {
                return ResourceManager.GetString("send_new_pass_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All records are success.
        /// </summary>
        public static string sync_success {
            get {
                return ResourceManager.GetString("sync_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sync Offline Operations.
        /// </summary>
        public static string sync_title {
            get {
                return ResourceManager.GetString("sync_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the image to change.
        /// </summary>
        public static string TapImage {
            get {
                return ResourceManager.GetString("TapImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string title_change_pass {
            get {
                return ResourceManager.GetString("title_change_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubications.
        /// </summary>
        public static string UbicationsViewTitle {
            get {
                return ResourceManager.GetString("UbicationsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to COLSTRAT!.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
